%% 任务书异步分时复用策略
function [Prop_Final, info] = Thruster_taskbook_async( ...
        v_cmd1, v_cmd2, Matrix_sub, faulty_thrusters, params)
%THRUSTER_TASKBOOK_ASYNC Reproduce the task-book per-thruster reuse rule.
%
% The primary/backup allocator first obtains a pure orbit pulse P_F and a
% pure attitude pulse P_T.  The task-book reuse rule then executes, for
% every thruster i, the two jobs in this order:
%
%   [0, P_T(i)]                 attitude job;
%   [P_T(i), P_T(i)+P_F_use(i)] orbit job;
%   P_F_use(i) = min(P_F(i), T - P_T(i)).
%
% Thus the available orbit time is calculated independently for every
% thruster.  Different thrusters can switch from attitude to orbit at
% different instants, hence this is asynchronous time-division reuse.  It
% intentionally preserves the task-book's per-thruster clipping behaviour
% for comparison with the synchronous group-preserving strategy.

    N = size(Matrix_sub, 2);
    T_ctrl = Get_Param(params, 'T', 0.4);
    Validate_Input();
    zero_command = zeros(3, 1);

    % Keep the allocation method unchanged: both requests are generated by
    % the existing minimal-primary / healthy-backup allocator.  Calling it
    % separately exposes its two requested pulse vectors before reuse.
    [~, force_info] = Thruster_invocation( ...
        v_cmd1, zero_command, Matrix_sub, faulty_thrusters, params);
    [~, attitude_info] = Thruster_invocation( ...
        zero_command, v_cmd2, Matrix_sub, faulty_thrusters, params);

    requested_force_axis = max(0, force_info.Prop_F_axis);
    requested_attitude_axis = max(0, attitude_info.Prop_T_axis);
    requested_force = sum(requested_force_axis, 2);
    requested_attitude = sum(requested_attitude_axis, 2);
    attitude_pulse = min(max(requested_attitude, 0), T_ctrl);
    remaining_time = max(0, T_ctrl - attitude_pulse);
    force_pulse = min(max(requested_force, 0), remaining_time);
    Prop_Final = attitude_pulse + force_pulse;

    % A clipped per-thruster total must retain the relative pulse shares of
    % its contributing axis groups.  These two row-wise factors preserve
    % the requested group composition while keeping every task in T.
    attitude_ratio = Pulse_Ratio(attitude_pulse, requested_attitude);
    force_ratio = Pulse_Ratio(force_pulse, requested_force);
    attitude_axis_pulse = requested_attitude_axis .* attitude_ratio;
    force_axis_pulse = requested_force_axis .* force_ratio;
    [schedule, scheduler] = Build_Asynchronous_Schedule( ...
        force_axis_pulse, attitude_axis_pulse);
    command = [v_cmd1(:); v_cmd2(:)];
    duty = Prop_Final / T_ctrl;
    force_duty = force_pulse / T_ctrl;
    attitude_duty = attitude_pulse / T_ctrl;

    info = struct();
    info.mode = 'asynchronous_time_division';
    info.reuse_strategy = 'asynchronous_time_division';
    info.allocation_strategy = 'primary_backup';
    info.solver = 'primary_backup_then_taskbook_per_thruster_clipping';
    info.fault_policy = 'retire_affected_complete_group';
    info.strict_paired_mode = force_info.strict_paired_mode && ...
        attitude_info.strict_paired_mode;
    info.uses_impulse_margin_fallback = ...
        force_info.uses_impulse_margin_fallback || ...
        attitude_info.uses_impulse_margin_fallback;
    info.nominal_reuse_count = max(force_info.nominal_reuse_count, ...
        attitude_info.nominal_reuse_count);
    info.structurally_reconfigurable = ...
        force_info.structurally_reconfigurable && ...
        attitude_info.structurally_reconfigurable;
    info.strictly_reconfigurable = force_info.strictly_reconfigurable && ...
        attitude_info.strictly_reconfigurable;
    info.Prop_F = requested_force;
    info.Prop_T = requested_attitude;
    info.Prop_F_used = force_pulse;
    info.Prop_T_used = attitude_pulse;
    info.Prop_F_axis = force_axis_pulse;
    info.Prop_T_axis = attitude_axis_pulse;
    info.Prop_F_axis_raw = requested_force_axis;
    info.Prop_T_axis_raw = requested_attitude_axis;
    info.Prop_6D = zeros(N, 1);
    info.Prop_Final = Prop_Final;
    info.schedule = schedule;
    info.scheduler = scheduler;
    info.scheduler_force_axis_suppressed = [];
    info.axis_strategy = Merge_Axis_Strategy( ...
        force_info.axis_strategy, attitude_info.axis_strategy);
    info.impulse_margin_unavailable_axes = unique([ ...
        force_info.impulse_margin_unavailable_axes(:); ...
        attitude_info.impulse_margin_unavailable_axes(:)]);
    info.force_scale = sum(force_pulse) / (sum(requested_force) + eps);
    info.attitude_scale = sum(attitude_pulse) / ...
        (sum(requested_attitude) + eps);
    info.force_scale_reason = 'taskbook_per_thruster_remaining_time';
    info.attitude_scale_reason = 'attitude_priority';
    info.orbit_wrench_raw = Matrix_sub * (requested_force / T_ctrl);
    info.attitude_wrench_raw = Matrix_sub * (requested_attitude / T_ctrl);
    info.orbit_wrench = Matrix_sub * force_duty;
    info.attitude_wrench = Matrix_sub * attitude_duty;
    info.orbit_cross_torque = norm(info.orbit_wrench(4:6));
    info.attitude_cross_force = norm(info.attitude_wrench(1:3));
    info.period_average_decoupled = ...
        info.orbit_cross_torque <= Get_Param(params, 'alloc_fit_tol', 1e-8) && ...
        info.attitude_cross_force <= Get_Param(params, 'alloc_fit_tol', 1e-8);
    info.duty = duty;
    info.command = command;
    info.actual = Matrix_sub * duty;
    info.residual = command - info.actual;
    info.reuse_scale = ones(N, 1);
    active_force = requested_force > 1e-12;
    info.reuse_scale(active_force) = force_pulse(active_force) ./ ...
        requested_force(active_force);
    info.orbit_keep_ratio = info.force_scale;
    info.att_keep_ratio = info.attitude_scale;
    info.max_raw_pulse = max(requested_force + requested_attitude);
    info.attitude_window = NaN;
    info.position_window = NaN;

    function Validate_Input()
        if size(Matrix_sub, 1) ~= 6
            error('Thruster_taskbook_async:InvalidMatrix', ...
                'Matrix_sub 必须是6xN控制效率矩阵。');
        end
        if numel(v_cmd1) ~= 3 || numel(v_cmd2) ~= 3
            error('Thruster_taskbook_async:InvalidCommand', ...
                '轨控和姿控指令必须分别包含三个分量。');
        end
        if ~isfinite(T_ctrl) || T_ctrl <= 0
            error('Thruster_taskbook_async:InvalidPeriod', ...
                '控制周期T必须为正数。');
        end
    end

    function strategy = Merge_Axis_Strategy(force_strategy, attitude_strategy)
        strategy = cell(2, 3);
        strategy(1, :) = force_strategy(1, :);
        strategy(2, :) = attitude_strategy(2, :);
    end

    function [schedule_out, scheduler_out] = ...
            Build_Asynchronous_Schedule(force_axis, attitude_axis)
        force = sum(force_axis, 2);
        attitude = sum(attitude_axis, 2);
        total = cell(N, 1);
        force_intervals = cell(N, 1);
        attitude_intervals = cell(N, 1);
        axis_intervals = cell(N, 1);
        for index = 1:N
            time = 0;
            % The task-book order is attitude first, then orbit.  Within a
            % category the three axis jobs are emitted in X/Y/Z order, so
            % every displayed coloured segment is also a real firing task.
            for axis = 1:3
                pulse = attitude_axis(index, axis);
                if pulse <= 1e-12
                    continue;
                end
                interval = [time, time + pulse];
                attitude_intervals{index}(end + 1, :) = interval; %#ok<AGROW>
                axis_intervals{index}(end + 1, :) = [interval, axis + 3]; %#ok<AGROW>
                time = interval(2);
            end
            for axis = 1:3
                pulse = force_axis(index, axis);
                if pulse <= 1e-12
                    continue;
                end
                interval = [time, time + pulse];
                force_intervals{index}(end + 1, :) = interval; %#ok<AGROW>
                axis_intervals{index}(end + 1, :) = [interval, axis]; %#ok<AGROW>
                time = interval(2);
            end
            total{index} = [attitude_intervals{index}; force_intervals{index}];
        end
        schedule_out = struct('enabled', true, 'intervals', {total}, ...
            'force_intervals', {force_intervals}, ...
            'attitude_intervals', {attitude_intervals}, ...
            'total_pulse', attitude + force, 'force_pulse', force, ...
            'attitude_pulse', attitude, 'job_starts', [], ...
            'axis_intervals', {axis_intervals});

        [peak_torque, peak_force] = Schedule_Peaks( ...
            force_intervals, attitude_intervals);
        torque_limit = Get_Param(params, 'scheduler_peak_torque_ratio', 0.25) * ...
            max(1e-12, max(abs(Matrix_sub(4:6, :)), [], 'all'));
        force_limit = Get_Param(params, 'scheduler_peak_force_ratio', inf) * ...
            max(1e-12, max(abs(Matrix_sub(1:3, :)), [], 'all'));
        scheduler_out = struct('peak_orbit_torque', peak_torque, ...
            'peak_attitude_force', peak_force, ...
            'peak_torque_limit', torque_limit, ...
            'peak_force_limit', force_limit, ...
            'peak_constraint_met', peak_torque <= torque_limit + 1e-12 && ...
                peak_force <= force_limit + 1e-12, ...
            'suppressed_force_axes', [], ...
            'force_axis_pulse', force_axis, ...
            'attitude_axis_pulse', attitude_axis, ...
            'status', 'taskbook_asynchronous');
    end

    function ratio = Pulse_Ratio(applied, requested)
        ratio = zeros(N, 1);
        active = requested > 1e-12;
        ratio(active) = applied(active) ./ requested(active);
    end

    function [peak_torque, peak_force] = ...
            Schedule_Peaks(force_intervals, attitude_intervals)
        edges = [0; T_ctrl];
        for index = 1:N
            edges = [edges; force_intervals{index}(:); ...
                attitude_intervals{index}(:)]; %#ok<AGROW>
        end
        edges = unique(edges);
        peak_torque = 0;
        peak_force = 0;
        for edge = 1:(numel(edges) - 1)
            if edges(edge + 1) - edges(edge) <= 1e-12
                continue;
            end
            time = 0.5 * (edges(edge) + edges(edge + 1));
            force_on = Interval_On(force_intervals, time);
            attitude_on = Interval_On(attitude_intervals, time);
            force_wrench = Matrix_sub * double(force_on);
            attitude_wrench = Matrix_sub * double(attitude_on);
            peak_torque = max(peak_torque, norm(force_wrench(4:6)));
            peak_force = max(peak_force, norm(attitude_wrench(1:3)));
        end
    end

    function on = Interval_On(intervals, time)
        on = false(N, 1);
        for index = 1:N
            interval = intervals{index};
            if isempty(interval)
                continue;
            end
            on(index) = any(time >= interval(:, 1) - 1e-12 & ...
                time < interval(:, 2) - 1e-12);
        end
    end

    function value = Get_Param(input_params, field_name, default_value)
        if isfield(input_params, field_name) && ...
                ~isempty(input_params.(field_name))
            value = input_params.(field_name);
        else
            value = default_value;
        end
    end
end
